# Config reference: https://alacritty.org/config-alacritty.html
[general]
live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 16

[font.bold]
family = "JetBrainsMonoNL NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL NF"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_title = true
option_as_alt = "Both"
opacity = 0.9
blur = true

[window.padding]
x = 0
y = 4

import = ["~/.config/alacritty/challenger-deep.toml"]
