# Usage: `brew bundle Brewfile`

update
upgrade

install ack
# Latest bash - Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash
install bash-completion
# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
install findutils
install git
install git-extras
install grep
install hub
install imagemagick --with-webp
install nvm
install rename
install ssh-copy-id
install tree
install webkit2png
install wget
install m-cli
install mas

cleanup
